version: '3.3'
services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mmn83/foodgram_backend
    env_file: .env
    volumes:
      - static_data:/app/static/
      - media_data:/app/media/
    depends_on:
      - db

  frontend:
    image: mmn83/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - 8000:80
    volumes:
      - ./nginx_production.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_data:/var/html/static/
      - media_data:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static_data:
  media_data: