# Generated by Django 3.2.20 on 2023-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_subscribe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='is_subscribed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
