# Generated by Django 3.2.20 on 2023-09-13 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_subscribe_is_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['recipe']},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ['ingredient']},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['recipe']},
        ),
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ['author']},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'ordering': ['tag']},
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_subscribe',
        ),
        migrations.AddField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subscribe'),
        ),
    ]
