# Generated by Django 3.2.20 on 2023-09-14 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_subscribe_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='is_in_shopping_cart',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='is_subscribed',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
